### ISSUE TITLE
Make WYSIWYG fields simple text areas or single line inputs

### ISSUE THREAD

**Issue by mandiwise** [redacademy/icef-winter-2017#5]
Please revisit anywhere you have implemented WYSIWYG editor for a custom field. In most cases, it seems like a simple text area or input would suffice.

Using a WYSIWYG editor give the user waaay more control to add whatever they want at that particular location on the page...and I'm guessing you don't actually want to do this.

**Comment by JohnWat92** [comment]
switched all WYSIWYG to text area instead
